### ISSUE TITLE
Open KV.leadingSpace for modification

### ISSUE THREAD

**Issue by trntv** [kevinburke/ssh_config#12] opened 2018-02-28 13:50 UTC
Hi, thank you for your package. Great work and saved me a lot of time implementing ssh_config parser myself :-) 

I'm using it in https://github.com/trntv/sshed for both reading and writing ssh_config. Now there is no other way to format KV entries except this
```
nodes = append(nodes, &ssh_config.KV{Key: "  HostName", Value: h.Hostname})
```
if you'll open ``leadingSpace``
```
nodes = append(nodes, &ssh_config.KV{Key: "HostName", Value: h.Hostname, LeadingSpace: 2})
```

btw, it would be nice to add more modification-specific functions eg. `AddHost`, `SetKV` etc

**Comment by kevinburke** [comment] 2018-03-04 22:04
Hmmm. I'd like to think for a little while about this, because I'm not sure it's a good idea to allow people to tweak these at will.

**Comment by trntv** [comment] 2018-03-05 09:45
we can at least create NewKV function

**Comment by lorencarvalho** [comment] 2021-01-15 23:13
@trntv is the underlying issue you're facing that the config output isn't formatted correctly?

```
Host *
HostName foo
Port 12345
```

vs.

```
Host *
  HostName foo
  Port 12345
```
 ?

If so, I am facing the same dillemma. Here is some simple code to reproduce:

```
func main () {
	pattern, _ := ssh_config.NewPattern("fakehost")
	patterns := []*ssh_config.Pattern{pattern}
	nodes := []ssh_config.Node{
		&ssh_config.KV{
			Key:   "HostName",
			Value: "fakehost.loren.pizza",
		},
	}
	host := ssh_config.Host{
		Patterns:   patterns,
		Nodes:      nodes,
	}
	cfg := ssh_config.Config{
		Hosts: []*ssh_config.Host{&host},
	}
	fmt.Println(cfg.String())
}
```
    
Which has the following output:

```
$ go run scratch.go 
Host fakehost
HostName fakehost.loren.pizza
```

but ideally it would output:

```
$ go run scratch.go 
Host fakehost
  HostName fakehost.loren.pizza
```

Thanks for the library, @kevinburke, it's great and obviously works well, this is just a cosmetic complaint.

**Comment by trntv** [comment] 2021-01-18 08:14
> @trntv is the underlying issue you're facing that the config output isn't formatted correctly?
yes, as far as i remember, it was it.

**Comment by kevinburke** [comment] 2022-03-31 18:34
I think the issue about output format should be fixed now. Going to close, feel free to reopen.

**Closed by kevinburke** 2022-03-31 18:34 UTC

**Comment by tekumara** [comment] 2023-10-28 23:29
I'm still running into the same problem eg: 
```
func main () {
	pattern, _ := ssh_config.NewPattern("fakehost")
	patterns := []*ssh_config.Pattern{pattern}
	nodes := []ssh_config.Node{
		&ssh_config.KV{
			Key:   "HostName",
			Value: "fakehost.loren.pizza",
		},
	}
	host := ssh_config.Host{
		Patterns:   patterns,
		Nodes:      nodes,
	}
	cfg := ssh_config.Config{
		Hosts: []*ssh_config.Host{&host},
	}
	fmt.Println(cfg.String())
}
```

produces this unindented output:

```
Host fakehost
HostName fakehost.loren.pizza
```

when using github.com/kevinburke/ssh_config v1.2.0
